### ISSUE TITLE
load and memory problems

### ISSUE THREAD

**Issue by thiagosouza** [feross/webtorrent-desktop#1145] opened 2017-03-01 18:11 UTC
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.18.0 (0.98.5) (64-bit)

**What operating system and version?**
Linux 16.04LTS

**What actually happened?**
I have some system monitors for memory, processing and network, and every time I open WebTorrent my load goes to 5, my memory gets full (the main process itself uses about 3GB) and my machine overheat.

Probably there is some memory leak, but I could not identify exactly where could be the problem. But it is just to open and my machine load goes very high.

Thanks!

**Comment by feross** [comment] 2017-03-01 21:22
Thanks for the issue. Duplicate of https://github.com/feross/webtorrent-desktop/issues/1054, probably related to WebRTC.

**Closed by feross** 2017-03-01 21:22 UTC
