### ISSUE TITLE
Issue with Display of Remaining Time, Download Speed

### ISSUE THREAD

**Issue by krisgopal128** [feross/webtorrent-desktop#1038] opened 2016-10-12 20:09 UTC
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.17.1 (0.97.2) 64Bit

**What operating system and version?**
Antergos Linux (Arch Linux Kernel 4.7.6-1) 64bit

**What did you do?**
Download multiple torrent file at same time 

**What did you expect to happen?**
To display correct download speed & remaining time 
![screenshot at 2016-10-12 23-59-31](https://cloud.githubusercontent.com/assets/13931326/19325951/8f0a1748-90d9-11e6-814a-12e3f472aea6.png)

**Comment by feross** [comment] 2016-10-13 03:31
This is probably due to the CPU being pegged at 100%. When that happens, [this `setInterval`](https://github.com/mafintosh/speedometer/blob/master/index.js#L8) will get delayed and so it looks like more bytes were downloaded in the time period than actually were.

Closing as duplicate of #619. The correct solution is for us to never use that many resources, but it's a known issue. Hopefully will be fixed before v1.0.

**Closed by feross** 2016-10-13 03:31 UTC
