### ISSUE TITLE
Finds peers and connects, but won't download

### ISSUE THREAD

**Issue by singpolyma** [feross/webtorrent-desktop#724] opened 2016-07-17 20:01 UTC
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

Version 0.8.1 (0.95.2)

**What operating system and version?**

Ubuntu 14.04 (i686)

---

I have a torrent of my own content (magnet:?xt=urn:btih:dc251a62ace7ee0ff24bb59b79ba79b6e7a019f7&dn=2016202%2000%20%E2%80%94%20Forematter) that I am testing with.  There are three seeds (one is me, and two are people I know who downloaded the torrent from my initial seed).  WebTorrent Desktop finds all three seeds, and if I look at my seed it even connects, but transmission-daemon alternates between `uI` or `uKI`, that is, WebTorrent Desktop has connected to my seed and just isn't asking for anything.  So the download never progresses.  I know the seed works because two people have downloaded it already.

**Comment by janat08** [comment] 2016-07-21 20:20
https://github.com/feross/webtorrent-desktop/issues/699

**Comment by dcposch** [comment] 2016-07-23 05:39
This is definitely a bug and we hope to have it fixed soon.
* Closing as a duplicate of #699 
* Also, it's probably a bug in the underlying library: https://github.com/feross/webtorrent

**Comment by feross** [comment] 2016-07-27 06:12
Re-opening because issue #699 was locked.

**Comment by feross** [comment] 2016-07-27 06:13
@singpolyma Roughly how large is the torrent of your own content that you're using?

**Comment by singpolyma** [comment] 2016-07-27 11:13
500 MB range

**Comment by feross** [comment] 2016-07-29 07:02
@dcposch This eliminates my theory that this was caused by extremely large torrents where the piece size is larger than 2GB. I think this is a bug in WebTorrent.

This issue is tracking the bug in the underlying library, so I'm going to close it here now: https://github.com/feross/webtorrent/issues/850

**Closed by feross** 2016-07-29 07:02 UTC
