### ISSUE TITLE
Won't play .m4a files

### ISSUE THREAD

**Issue by HughIsaacs2** [feross/webtorrent-desktop#1107] opened 2017-01-19 04:09 UTC
Webtorrent Desktop (Version 0.17.2 (0.97.2) (64-bit - Windows 10) as of me writing this) supports playback of .aac files but not .m4a files, I've tested simply changing the file extension of the .m4a files in question to .aac and it plays but it returns an error if the extension is .m4a and sends the user off to play it in an external player.

**Comment by feross** [comment] 2017-01-19 12:07
That's strange. Can you email me the file in question? (Email is on my website's [bio page](http://feross.org/about/))

I think our detection of invalid codecs is a bit janky, since it relies on waiting a bit and checking if any audio was decoded. If you send me the file, I can confirm this theory.

**Comment by feross** [comment] 2017-02-15 21:18
Confirmed! Version 0.17.2 (on Windows 64) can't play the .m4a file in question. However I just tested with version 0.18.0 and it works great. Weirdly, both 0.17.2 and 0.18.0 (on macOS) can play the file.

Looks like this was a Chromium bug specific to Windows that is now fixed.

 B

**Closed by feross** 2017-02-15 21:18 UTC
