### ISSUE TITLE
Bug: Player window disappears when playing audio only .mov file

### ISSUE THREAD

**Issue by Flet** [feross/webtorrent-desktop#340] opened 2016-04-07 04:11 UTC
File from archive.org: https://archive.org/download/AphexTwinBOACAphex/AphexTwinBOACAphex_archive.torrent

When the file is played, the player is briefly shown then disappears (perhaps as it tries to resize itself). The audio plays just fine, however there is no way to control the player or jump back to the torrent list.

**Comment by feross** [comment] 2016-04-07 04:17
What do you mean by it disappears? Does the entire window disappear? Or does the window contents go away leaving only the gray background?

Maybe the window is moving to another monitor when you press play. I haven't tested how it behaves with multiple monitors.

**Comment by grunjol** [comment] 2016-04-07 04:22
I think the problem is the file is treated as video file (.mov) and the window is autoresized to 0x0 (the video size),

**Comment by Flet** [comment] 2016-04-07 04:35
Yep, I think @grunjol is correct. Logging the dimension in  `onLoadedMetadata` in `player.js`:
```js
dimensions Object {width: 0, height: 0}
```

Maybe check for a minimum height/width and do not resize if its too low?

**Comment by feross** [comment] 2016-04-07 04:35
PR incoming

**Closed** 2016-04-08 04:27 UTC
Labels: bug
