### ISSUE TITLE
black screen when adding magnet?

### ISSUE THREAD

**Issue by nickdoonan** [feross/webtorrent-desktop#346] opened 2016-04-07 10:26 UTC
**What version of WebTorrent Desktop?**
Unknown. Latest beta?

**What operating system and version?**
Win 10 x64
**What did you do?**
Manually added torrent file, copied and pasted magnet link. Waited a long time.
**What did you expect to happen?**
Torrent to load and start playing
**What actually happened?**
black screen. noth
![webtorent](https://cloud.githubusercontent.com/assets/15344709/14348311/9d12040a-fcb3-11e5-9691-763327229d86.PNG)
ing.

**Comment by yciabaud** [comment] 2016-04-08 13:08
@nickdoonan has reported having an error in the console before adding the magnet:
`Not allowed to load local resource: file:///C:/Users/(blankedout)\AppData\Local\WebTorrent\app-0.3.2\resources\app.asar\renderer\webtorrent.html`

**Comment by dcposch** [comment] 2016-04-16 07:57
Unfortunately, I have no way to reproduce this.

* I'll try to add an error handler that reports Javascript exceptions, so we can debug stuff like this
* In the meantime, if it happens again, could you go to View > Developer > Developer Tools? Then go to the Console tab and paste the error here.

**Comment by feross** [comment] 2016-05-13 02:24
Closing due to lack of new information.

**Closed by feross** 2016-05-13 02:24 UTC
Labels: bug
