### ISSUE TITLE
error: attempt to write outside buffer bounds

### ISSUE THREAD

**Issue by blackcatvinu** [feross/webtorrent-desktop#472] opened 2016-05-09 12:30 UTC
WebTorrent Desktop version 0.3.3

OS windows 10

I install webtorrent first time on my laptop.
i open webtorrent and try to play torrent file,
it gives me error: attempt to write outside buffer bounds.

**Comment by feross** [comment] 2016-05-09 14:42
@blackcatvinu Did you find that error message in "View > Developer > Show WebTorrent Process"?

Were you playing one of the built-in torrents or one of your own?

**Comment by iRuisu** [comment] 2016-05-09 19:36
I was getting this issue too. Running the app in admin mode fixed the problem.

**Comment by iRuisu** [comment] 2016-05-09 19:42
Also getting the same problem via magnet links provided by provided by external sources. Developer console is just line after line of the following error "buffer.js:703 Uncaught RangeError: attempt to write outside buffer bounds"

**Comment by vsych** [comment] 2016-05-18 21:28
i think its webtorrent issue 
buffer.js:772 Uncaught RangeError: Attempt to write outside buffer bounds
Buffer.write @ buffer.js:772
fromString @ buffer.js:238
Buffer.from @ buffer.js:131
Buffer @ buffer.js:112
Wire.handshake @ .../node_modules/bittorrent-protocol/index.js:192
Peer.handshake .../node_modules/webtorrent/lib/peer.js:190
Peer.onConnect @.../node_modules/webtorrent/lib/peer.js:147
(anonymous function) @ .../node_modules/webtorrent/lib/torrent.js:1576
g @ events.js:286
emitNone @ events.js:86
emit @ events.js:185
afterConnect @ net.js:1067

**Comment by feross** [comment] 2016-05-29 10:46
This is so odd. It's crashing inside of the node `Buffer` constructor. And it's on a line that's just creating a buffer from a 20 byte hex string.

https://github.com/feross/bittorrent-protocol/blob/1cd12f4bcc0394b2311247a41ab60d912b89a00b/index.js#L192

**Comment by feross** [comment] 2016-05-30 02:07
Closing this issue in favor of the one on the main webtorrent repo: https://github.com/feross/webtorrent/issues/820

We figured out what the root cause of this issue is, finally!

**Closed by feross** 2016-05-30 02:07 UTC
Labels: need more info
