### ISSUE TITLE
Playback freeze, waiting for buffer

### ISSUE THREAD

**Issue by dispix** [feross/webtorrent-desktop#446] opened 2016-04-28 08:44 UTC
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.3.3 (0-a5366c3)
**What operating system and version?**
OSX Yosemite 10.10.5
**What did you do?**
Was watching a torrent video
**What did you expect to happen?**
Playback running smoothly
**What actually happened?**
Video paused with loading information just like it needed more torrent parts to go on, but there was more than enough to continue playing. Going back on the main screen and clicking on the play button fixed it.

**Comment by feross** [comment] 2016-04-28 10:08
This is odd. I've never seen this happen, but I'll keep an eye out for it. If this happens again for you, can you click "View > Developer > Show WebTorrent Process" and post the log into this issue?

**Comment by dispix** [comment] 2016-04-28 10:10
Yeah I forgot to get a look into the processes but it happened a couple of
times already so I'll try to remember and do that :)

Octave Raimbault
On Apr 28, 2016 12:08, "Feross Aboukhadijeh" <notifications@github.com>
wrote:

This is odd. I've never seen this happen, but I'll keep an eye out for it.
If this happens again for you, can you click "View > Developer > Show
WebTorrent Process" and post the log into this issue?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/feross/webtorrent-desktop/issues/446#issuecomment-215376240>

**Comment by feross** [comment] 2016-04-28 10:15
Awesome, thank you. The log would be extremely helpful.

**Comment by dispix** [comment] 2016-05-02 14:49
Hum, where am I supposed to get details on the processes ? When I click on "Show WebTorrent Process" all I have is a small window with the project logo. Also, may not be related but I have this error repeating multiple time in the console :

`(node) warning: possible EventEmitter memory leak detected. 11 connect listeners added. Use emitter.setMaxListeners() to increase limit.addListener @ events.js:248
events.js:252 console.trace()addListener
events.js:248 (node) warning: possible EventEmitter memory leak detected. 11 connect listeners added. Use emitter.setMaxListeners() to increase limit.addListener @ events.js:248`

**Comment by feross** [comment] 2016-05-04 14:05
The EventEmitter memory leak warning can be safely ignored.

**Comment by feross** [comment] 2016-05-04 14:06
When you click "Show WebTorrent Process" an Inspector window should also open that contains a log that you can copy out.

**Comment by feross** [comment] 2016-06-01 08:59
Closing since we can't reproduce this.

**Closed by feross** 2016-06-01 08:59 UTC
Labels: need more info

**Comment by JaKXz** [comment] 2016-07-21 06:42
I can confirm I'm seeing this issue on `Version 0.8.1 (0.95.2)`. Commenting to remind myself to post logs soon.
