### ISSUE TITLE
Always making itself as default program for torrents.

### ISSUE THREAD

**Issue by KashifAnwaar** [feross/webtorrent-desktop#734] opened 2016-07-23 07:24 UTC
**What version of WebTorrent Desktop?** 
WebTorrent v0.9.0

**What operating system and version?**
Windows 7 64bit

**What did you do?**
Just opened

**What did you expect to happen?**
Don't set itself as default program for torrents without asking the user

**What actually happened?**
Everytime it sets itself as  default program for torrents, especially very painful when it sets also for magnet links.

**Comment by demoneaux** [comment] 2016-07-23 08:11
Hi! This issue is a duplicate of #367. We’re working on fixing this! If you’ve got any other issues feel free to report them. Closing this for now.

**Closed by demoneaux** 2016-07-23 08:11 UTC

**Comment by KashifAnwaar** [comment] 2016-07-23 08:19
#367 was only for magnets, i am here reporting for all torrent associations.

**Comment by feross** [comment] 2016-07-23 09:37
@KashifAnwaar I just updated the title to include all torrent associations. Thanks for opening an issue.

**Comment by KashifAnwaar** [comment] 2016-07-23 09:56
@feross I am fan of yours, thanks for the reply.

**Comment by feross** [comment] 2016-07-23 10:08
@KashifAnwaar Thanks 👍

**Comment by KashifAnwaar** [comment] 2016-07-23 12:46
It's my pleasure
