### ISSUE TITLE
Limit speed

### ISSUE THREAD

**Issue by bymafmaf** [feross/webtorrent-desktop#440] opened 2016-04-25 21:40 UTC
Version 0.3.3
Mac OSX 10.11.4

I've searched all menus but couldn't find an option to limit download and/or upload speeds, which is really useful to use when your connection isn't perfect or you're running on a quota limited network.

**Comment by raeesiqbal** [comment] 2016-04-27 11:17
Duplicate of #435

**Closed** 2016-04-28 10:23 UTC
