### ISSUE TITLE
Failed setup on windows 7 

### ISSUE THREAD

**Issue by jjm25** [feross/webtorrent-desktop#416] opened 2016-04-15 20:13 UTC
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
v0.3.3
**What operating system and version?**

Windows 7 64 bit

**What did you do?**
Downloaded the Windows setup from https://webtorrent.io/desktop and ran it.

**What did you expect to happen?**
Setup should install WebTorrent Desktop successfully.

**What actually happened?**
Setup failed,well not even that as it appears to be an ok installation but the app is not responding at all when trying to open it and this is the log:

2016-04-15 21:49:10> Program: Starting Squirrel Updater: --install .
2016-04-15 21:49:10> Program: Starting install, writing to C:\Users\Bojan\AppData\Local\SquirrelTemp
2016-04-15 21:49:10> Program: About to install to: C:\Users\Bojan\AppData\Local\WebTorrent
2016-04-15 21:49:10> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Bojan\AppData\Local\WebTorrent\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3f.MoveNext()
2016-04-15 21:49:10> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Bojan\AppData\Local\SquirrelTemp
2016-04-15 21:49:10> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-04-15 21:49:10> ApplyReleasesImpl: Writing files to app directory: C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3
2016-04-15 21:49:12> ApplyReleasesImpl: Moving file C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\lib\net45\content_resources_200_percent.pak to C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\content_resources_200_percent.pak
2016-04-15 21:49:12> ApplyReleasesImpl: Moving file C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\lib\net45\ffmpeg.dll to C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\ffmpeg.dll
2016-04-15 21:49:12> ApplyReleasesImpl: Moving file C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\lib\net45\d3dcompiler_47.dll to C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\d3dcompiler_47.dll
2016-04-15 21:49:12> ApplyReleasesImpl: Moving file C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\lib\net45\content_shell.pak to C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\content_shell.pak
2016-04-15 21:49:12> ApplyReleasesImpl: Moving file C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\lib\net45\icudtl.dat to C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\icudtl.dat
2016-04-15 21:49:12> ApplyReleasesImpl: Moving file C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\lib\net45\libEGL.dll to C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\libEGL.dll
2016-04-15 21:49:12> ApplyReleasesImpl: Moving file C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\lib\net45\libGLESv2.dll to C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\libGLESv2.dll
2016-04-15 21:49:12> ApplyReleasesImpl: Moving file C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\lib\net45\LICENSE to C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\LICENSE
2016-04-15 21:49:12> ApplyReleasesImpl: Moving file C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\lib\net45\msvcp120.dll to C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\msvcp120.dll
2016-04-15 21:49:12> ApplyReleasesImpl: Moving file C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\lib\net45\msvcr120.dll to C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\msvcr120.dll
2016-04-15 21:49:12> ApplyReleasesImpl: Moving file C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\lib\net45\natives_blob.bin to C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\natives_blob.bin
2016-04-15 21:49:12> ApplyReleasesImpl: Moving file C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\lib\net45\node.dll to C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\node.dll
2016-04-15 21:49:12> ApplyReleasesImpl: Moving file C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\lib\net45\snapshot_blob.bin to C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\snapshot_blob.bin
2016-04-15 21:49:12> ApplyReleasesImpl: Moving file C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\lib\net45\ui_resources_200_percent.pak to C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\ui_resources_200_percent.pak
2016-04-15 21:49:12> ApplyReleasesImpl: Moving file C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\lib\net45\WebTorrent.exe to C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\WebTorrent.exe
2016-04-15 21:49:12> ApplyReleasesImpl: Moving file C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\lib\net45\vccorlib120.dll to C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\vccorlib120.dll
2016-04-15 21:49:12> ApplyReleasesImpl: Moving file C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\lib\net45\squirrel.exe to C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\squirrel.exe
2016-04-15 21:49:12> ApplyReleasesImpl: Moving file C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\lib\net45\xinput1_3.dll to C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\xinput1_3.dll
2016-04-15 21:49:13> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Bojan\AppData\Local\WebTorrent\app-0.3.3\WebTorrent.exe]
2016-04-15 21:49:13> ApplyReleasesImpl: Starting fixPinnedExecutables
2016-04-15 21:49:13> ApplyReleasesImpl: Examining Pin: chrome - Shortcut.lnk
2016-04-15 21:49:13> ApplyReleasesImpl: Examining Pin: Windows Explorer.lnk
2016-04-15 21:49:13> ApplyReleasesImpl: Examining Pin: Windows Media Player.lnk
2016-04-15 21:49:13> ApplyReleasesImpl: Fixing up tray icons
2016-04-15 21:49:13> ApplyReleasesImpl: Failed to delete key: C:\Users\Bojan\AppData\Local\WebTorrent\Update.exe: System.UnauthorizedAccessException: Cannot write to the registry key.
   at System.ThrowHelper.ThrowUnauthorizedAccessException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.EnsureWriteable()
   at Microsoft.Win32.RegistryKey.DeleteValue(String name)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassfb.<>c__DisplayClassfd.<unshimOurselves>b__f8()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
2016-04-15 21:49:13> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.UnauthorizedAccessException: Cannot write to the registry key.
   at System.ThrowHelper.ThrowUnauthorizedAccessException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.EnsureWriteable()
   at Microsoft.Win32.RegistryKey.DeleteValue(String name)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassfb.<>c__DisplayClassfd.<unshimOurselves>b__f8()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassfb.<unshimOurselves>b__f7(String x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__f5(RegistryView view)
2016-04-15 21:49:13> ApplyReleasesImpl: Failed to delete key: C:\Users\Bojan\AppData\Local\WebTorrent\Update.exe: System.UnauthorizedAccessException: Cannot write to the registry key.
   at System.ThrowHelper.ThrowUnauthorizedAccessException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.EnsureWriteable()
   at Microsoft.Win32.RegistryKey.DeleteValue(String name)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassfb.<>c__DisplayClassfd.<unshimOurselves>b__f8()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
2016-04-15 21:49:13> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.UnauthorizedAccessException: Cannot write to the registry key.
   at System.ThrowHelper.ThrowUnauthorizedAccessException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.EnsureWriteable()
   at Microsoft.Win32.RegistryKey.DeleteValue(String name)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassfb.<>c__DisplayClassfd.<unshimOurselves>b__f8()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassfb.<unshimOurselves>b__f7(String x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__f5(RegistryView view)
2016-04-15 21:49:13> ApplyReleasesImpl: cleanDeadVersions: for version 0.3.3
2016-04-15 21:49:13> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.3.3

**Comment by feross** [comment] 2016-04-16 01:19
@jjm25 Did you by chance run the installer twice? If you do that (and while the application is still running), then you will get errors.

See issue here: https://github.com/Squirrel/Squirrel.Windows/issues/652

**Comment by feross** [comment] 2016-04-16 01:19
You should check the tray icon, as WebTorrent may still be running in the tray.

**Comment by kimare16** [comment] 2016-04-16 21:58
I also tried to install webtorrent on w7 32bit version and came up with the same error. Verified the task manager nothing running rebooted and everything still coulndt manage to install it. The computer has been formated a few weeks before the only thing there running is kodi and a few emulatores. Nothing that would prevent the instalation of webtorrent.

**Comment by jjm25** [comment] 2016-04-16 22:05
No I didn't run the installer twice,the app isn't running at all...anyplace,it is totally unresponsive

**Comment by kapitanluffy** [comment] 2016-04-20 00:58
Created an issue a few days ago in the wrong repo, almost similar issue.

https://github.com/feross/webtorrent/issues/739

**Comment by jjm25** [comment] 2016-04-23 22:41
Tried installing on my older PC also with windows 7 64bit as well and the app workes fine...so I have no idea what is different that on one it works fine and on the other it just doesn't respond...

**Comment by jjm25** [comment] 2016-04-26 21:36
So the weirdest thing happened that I wanted to share,I reinstalled my Windows yesterday,thinking that it would help but it didn't,same problem as before,today I started the program just for the heck of it and the program is responding and working well...How this happened I can't explain...

**Comment by AliBASE** [comment] 2016-05-04 09:49
and me the same problem.I using windows 7 32bit Ultimate

**Comment by happlebao** [comment] 2016-05-15 20:21
any news?

> System.UnauthorizedAccessException: Cannot write to the registry key.


my app got same problem with Squirrel

**Comment by feross** [comment] 2016-05-17 01:46
@kapitanluffy @kimare16 AliBASE If you were having issues installing WebTorrent Desktop on Windows 32 bit, you should know that v0.4.0 (released a few days ago) has support for Windows 32 bit now, so it should work fine for you. Enjoy!

You an grab the latest installer from: https://webtorrent.io/desktop

**Comment by kimare16** [comment] 2016-05-17 12:59
humm maybe that was the problem since I updated to w10 but the 32bit version cause of my machine being a bit oldish and still wasn´t running. Thanks mate I will give it a go later on and post the results here

**Comment by feross** [comment] 2016-05-17 23:30
Going to close this issue now, since the 32-bit issue is fixed, and I can't reproduce the original "Failed to delete key: Cannot write to the registry key." error. It may be fixed in WebTorrent v0.4 because Squirrel.Windows was updated.

**Closed by feross** 2016-05-17 23:30 UTC
Labels: need more info
