### ISSUE TITLE
Auto Delete torrent files

### ISSUE THREAD

**Issue by pallavmac** [feross/webtorrent-desktop#1150] opened 2017-03-11 05:44 UTC
Once a file has started downloading, the original torrent file is no longer necessary. So give the user to delete a torrent file once it has been added is really useful.

**Comment by manixate** [comment] 2017-03-17 15:17
Looks similar to #1139

**Comment by feross** [comment] 2017-03-17 17:49
Duplicate of #1139.

**Closed by feross** 2017-03-17 17:49 UTC
