### ISSUE TITLE
After adding about 20 magnet links the Webtorrent desktop client failed to add more

### ISSUE THREAD

**Issue by SiegeLionT** [feross/webtorrent-desktop#651] opened 2016-06-19 02:35 UTC
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.7.2 (0.94.3)
**What operating system and version?**
win10 14332
**What did you do?**
I added 20 or more magnet links to this webtorrent client and was trying to add more. Usually the client would beep when a link is added, but it didn't beep. Found that the client didn't add links.
**What did you expect to happen?**
I thought that the client should be able to download multiple links at the same time, seems there's a limit.
Deleted a few and still not working. 
**What actually happened?**
Haven't worked out the problem yet.

**Comment by dcposch** [comment] 2016-06-23 01:18
Thanks for the bug report!

If you run into this again, could you click on View > Developer > Show WebTorrent Process and see if there are any errors in the console? If there are, please paste them here.

**Comment by SiegeLionT** [comment] 2016-06-23 06:00
The preserve log tick is not ticked by default. No log can be seen now. The program works pretty well now. When the problem happen again I will reply to you. 
Thanks for your work!
Cheers!

**Comment by feross** [comment] 2016-07-27 06:06
This issue was probably caused by an uncaught exception (we have a few, listed here: #689) and just required a restart to fix.

@SiegeLionT If this happens again, do copy out the debug logs to help us out. But we'll keep working on squashing these exceptions until there's none left. I'm going to close this issue now since we don't have any info here to work from.

**Closed by feross** 2016-07-27 06:06 UTC
