### ISSUE TITLE
Downloads files from a large torrent that I didn't choose

### ISSUE THREAD

**Issue by ethaniel** [feross/webtorrent-desktop#1089] opened 2016-11-30 15:30 UTC
When I import a large torrent (a whole season from series) and quickly deselect the files that I don't need to be downloaded, WTD ignores my selection and keeps downloading the whole torrent.

For example, I need only 1 file out of 10. I import the torrent. Deselect 9 files. But WTD keeps downloading them like nothing happened.

**Comment by feross** [comment] 2016-12-09 09:52
Duplicate of https://github.com/feross/webtorrent-desktop/issues/719

**Closed by feross** 2016-12-09 09:52 UTC
