### ISSUE TITLE
Cinnamon on linux keeps on crashing by webtorrent

### ISSUE THREAD

**Issue by Shankymahajan** [feross/webtorrent-desktop#696] opened 2016-06-30 09:31 UTC
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.8.0

**What operating system and version?**
linux (linux mint 18 beta)

**What actually happened?**

Whenever I start webtorrent . Cinnamon keeps on crashing and force me to restart it.

**Comment by demoneaux** [comment] 2016-06-30 09:39
This seems like a duplicate of #532. Closing this instead.

**Closed by demoneaux** 2016-06-30 09:39 UTC
