### ISSUE TITLE
Adding WebTorrent Support to Existing Clients

### ISSUE THREAD

**Issue by Edward-Stryfe** [feross/webtorrent-desktop#1053] opened 2016-10-20 22:28 UTC
So how would one go about adding webtorrent support into an open source torrent application that already has support for DHT, PEX, UDP, HTTP, etc. I know of one for sure that has some javascript in it called DELUGE https://github.com/deluge-torrent/deluge but the majority of the code is Python with a Significant sum being JS and the rest being CSS. 

So is it possible to add WT compatibility to any client despite it's base?(ie, python, C++, etc) or does it need to be pure JS? Would it be as simple as adding in some variables and files for the compatibility or would the whole client need to be re-worked with WT braided into it? 

Cause as of now to my knowledge there's no support for any other protocol and WON'T be with the webtorrent-desktop application, and I've yet to see any projects come up that have universal support in mind or heard news of bigger BT client projects discuss adding in WT.

**Comment by grunjol** [comment] 2016-10-21 16:09
I think you should check this https://github.com/feross/webtorrent/issues/369

**Comment by Edward-Stryfe** [comment] 2016-10-22 04:54
Thanks it's good to know that a big torrent brand has already added a plugin for WT albeit a 60mb plugin but a spectacular achievement. I've looked long and hard for this thank you. I'll have to see what I could do to contribute to the initiative to get WT added into libtorrent

**Comment by kopy-kate** [comment] 2016-10-27 13:05
This is what will eventually kick off the project and make it go mainstream, in my opinion. I'm surprised more people haven't heard of this project.. it has massive potential.

**Comment by feross** [comment] 2016-10-30 22:35
Yeah, it's true that the Vuze implementation is a bit hacky. Still, better than nothing! I look forward to it improving and hopefully not requiring a whole browser to be shipped in the plugin.

**Comment by feross** [comment] 2016-10-30 22:35
Closing as duplicate of https://github.com/feross/webtorrent/issues/369

**Closed by feross** 2016-10-30 22:35 UTC
