### ISSUE TITLE
About form messed up

### ISSUE THREAD

**Issue by TakeruLunsford** [feross/webtorrent-desktop#354] opened 2016-04-07 20:42 UTC
**What version of WebTorrent Desktop?** 0.3.3

**What operating system and version?** Arch Linux

**What did you do?** Opened the 'About'

**What did you expect to happen?** To see a proper About form

**What actually happened?** Messed up text appeared in the form: 
![screenshot at 2016-04-07 15 38 36](https://cloud.githubusercontent.com/assets/2075754/14366189/37c18a52-fcd7-11e5-9ddb-a5777c6e4a33.png)

EDIT: I relaunched it and it was fine the second time.

**Comment by feross** [comment] 2016-04-08 08:46
This is extremely odd.

It seems that part of the page html and the `index.css` file showed up inside the box. The `index.css` file isn't even referenced from the about page, so I don't get how this could happen.

Do you have memory corruption or a bad hard disk perhaps?

**Comment by TakeruLunsford** [comment] 2016-04-08 19:25
No, I've checked the disk, and there's no issues. I think it might've just been a random hiccup. Every time I've started it since taking that screenshot, it's displayed fine. The main form performed fine when this issue happened.

**Comment by ungoldman** [comment] 2016-04-08 21:45
If anything it's an election bug as I don't believe we have any direct control over the about window.

**Comment by feross** [comment] 2016-04-08 22:13
@ungoldman, the About window on non OS X platforms is just a BrowserWindow
since those don't get them for free like OS X.

**Comment by feross** [comment] 2016-04-08 22:17
This sounds like a fluke and we can't reproduce it. Closing.

**Closed by feross** 2016-04-08 22:17 UTC
Labels: need more info
