### ISSUE TITLE
Webtorrent can't detect or can't play Merged / Forced / Softcoded subtitles 

### ISSUE THREAD

**Issue by Droyk** [feross/webtorrent-desktop#685] opened 2016-06-28 00:15 UTC
**You are about to read some bad English. and I am really sorry about it. I am not a native English speaker.**
So as the title says Webtorrent can't detect or play  softcoded /merged /forced subtitles I don't know why 
but I tried 4 videos and all of the 4 videos have merged subtitles but Webtorrent didn't detect any of those subtitles. 

- **What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Ans. I am using Version 0.8.1 (0.95.2)

- **What operating system and version?**
Ans. I am using Windows 10 x64

- **What did you do?**
Ans. Nothing. 

- **What did you expect to happen?**
Ans. Well I expected Webtorrent to show the forced /merged /Softcoded subtitle.    

- **What actually happened?**
Ans. Video started but can't really see the Merged / Forced subtitle.

**Comment by mathiasvr** [comment] 2016-06-28 00:34
Yes this is inconvenient. Closing as duplicate of #526.

**Closed by mathiasvr** 2016-06-28 00:34 UTC

**Comment by Droyk** [comment] 2016-06-28 00:41
@mathiasvr any ETA when will you guys fix this?

**Comment by mathiasvr** [comment] 2016-06-28 01:13
@Droyk This issue is a bit complicated and has not (yet) been added to the `v1.0` milestone so it is hard to say. It depends on whether someone starts working on it.
