### ISSUE TITLE
Problems...

### ISSUE THREAD

**Issue by sujankafle** [feross/webtorrent-desktop#461] opened 2016-05-06 01:42 UTC
**v0.3.3** 

**Windows 7 64-bit**

-Can't select or dselect which files to download.
-Can't change the download location for files.
-Overall time left, total time and time information on seek is needed.
-Ability to add subtitles and change the aspect ratio is needed.

Other than this it works like a charm. Done a great work by making this. Keep up the good work.

And could you explain why my normal torrent  client gives me a speed of 95-130 KBps but with Webtorrent i get from 500 KBps upto 12 MBps when my internet speed is just 1/1Mbps.

**Comment by feross** [comment] 2016-05-08 14:44
Thanks for the positive feedback! In the future, please open separate issues for each suggestion. It makes it easier to keep track of each issue individually.

> -Can't select or dselect which files to download.

Known issue. Duplicate of https://github.com/feross/webtorrent-desktop/issues/360

> -Can't change the download location for files.

Known issue. See https://github.com/feross/webtorrent-desktop/pull/426

> -Overall time left, total time and time information on seek is needed.

Duplicate of https://github.com/feross/webtorrent-desktop/issues/351

> -Ability to add subtitles and change the aspect ratio is needed.

This feature is already added on `master` and will be available in the next release.

> And could you explain why my normal torrent client gives me a speed of 95-130 KBps but with Webtorrent i get from 500 KBps upto 12 MBps when my internet speed is just 1/1Mbps.

There was a bug in web seeding in a previous version of the `webtorrent` npm package where a ton of requests would be sent to the web seed server and that would inflate the download speed. It's fixed in the current version of `webtorrent` and will be released in the next version of WebTorrent Desktop.

Cheers!

**Closed by feross** 2016-05-08 14:44 UTC
Labels: question
