### ISSUE TITLE
Webtorrent renderer process reliably crashes in Windows 7

### ISSUE THREAD

**Issue by dcposch** [feross/webtorrent-desktop#577] opened 2016-05-24 14:03 UTC
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.6.0 (released, but not yet in the autoupdater)

**What operating system and version?**
Windows 7 Home 64-bit

**Steps to reproduce**
* Start WebTorrent Desktop with all torrents turned off
* Open the webtorrent renderer process
* Start a single torrent

Webtorrent renderer process immediately dies:

![image](https://cloud.githubusercontent.com/assets/169280/15506736/91cc25f0-217d-11e6-8c43-40ce6a886d67.png)

**Comment by dcposch** [comment] 2016-05-24 14:09
@feross before we send 0.6.0 to the auto updater, I think we should:
*  Verify that the windows version works in your VM. It would also be nice to know whether this bug happens on all Windows 7 computers, or whether there's something specifically wrong on my x220.
* `npm publish`

It works great on Mac as far as I can tell, including the autoupdater. (After testing, it successfully downgraded itself to 0.5.1 lol)

**Comment by feross** [comment] 2016-05-25 01:15
Weird. Checking this out now.

**Comment by feross** [comment] 2016-05-26 05:06
Root cause: https://github.com/electron/electron/issues/5629

**Comment by feross** [comment] 2016-06-01 08:36
This was fixed by temporarily disabling WebRTC on Windows to get WebTorrent Desktop v0.6.1 out the door.

This will be undone in v0.7.0.

**Closed by feross** 2016-06-01 08:36 UTC
Labels: bug
