### ISSUE TITLE
VLC won't minimize and have title

### ISSUE THREAD

**Issue by janat08** [feross/webtorrent-desktop#700] opened 2016-07-01 23:11 UTC
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.8.1 (0.95.2)
**What operating system and version?**
Ubuntu 16.04
**What did you do?**
Open unsupported format in vlc
**What did you expect to happen?**
vlc to have title displaying played file in top bar rather than localhost and minimize player
**What actually happened?**
played file isn't shown, and it won't minimize (vlc).

**Comment by janat08** [comment] 2016-07-02 02:56
Minimize thing may be ubuntu peculiarity

**Comment by Goldob** [comment] 2016-07-09 14:08
I confirm both issues occuring in Windows 10. Although in my case it's not that the window won't minimize - rather than it is always on top _unless_ minimized.

**Comment by mathiasvr** [comment] 2016-07-09 14:35
VLC currently runs with the following arguments: 
`--play-and-exit`, `--video-on-top`, `--no-video-title-show`, `--quiet`
Personally I find _always on top_ annoying, so maybe we should discuss the default options?

**Comment by Goldob** [comment] 2016-07-09 15:02
In other words: _it's not a bug, it's a feature_.

Anyway, I also think it's irritating and my vote is for getting rid of `--video-on-top` flag.

Regarding the title, maybe we could pass **sanitized** video title with `--video-title=<string>`. Details [here](https://wiki.videolan.org/VLC_command-line_help/).

**Comment by mathiasvr** [comment] 2016-07-09 17:20
I think `--video-on-top` is there because the vlc window is not focused otherwise, however this can probably be fixed in another way. I like that the title is not displayed on the video, why do you want this?

**Comment by mathiasvr** [comment] 2016-07-09 17:28
I think the `--video-on-top` is there because the vlc window does not auto-fucus, but this can probably be solved in a different way. The title can be set with `--meta-title`.

**Comment by feross** [comment] 2016-07-27 21:44
@mathiasvr That's right. `--video-on-top` is a workaround for a VLC issue. As far as I've been able to tell, there's no way to tell VLC to take focus without using `--video-on-top`. There's a [forum thread](https://forum.videolan.org/viewtopic.php?t=84522) about it, and I believe there was a bug report as well, but I can't find it now.

If someone finds a way to force VLC to come to the front without needing `--video-on-top`, I'm happy to merge that! I also find floating on top annoying.

As for setting the title in VLC, here's a PR for that: https://github.com/feross/webtorrent-desktop/pull/746

**Closed** 2016-07-27 23:04 UTC
Labels: bug

**Comment by fjeddy** [comment] 2017-11-16 01:35
This should at the very least be an option in the settings.

I get that it's beneficial that VLC auto-focuses to itself when you play the video, it's after all what you're trying to do. But, the benefit of having VLC auto-focusing and not having to switch windows yourself, is a fraction compared to the annoyance of not being able to minimize / switch windows while the video is running.

It might be a different experience for you as the owner, and I assume it is since you've chosen to see the benefit of auto-focusing as more useful then always-on-top is annoying. But for me personally, this is a reason in itself to not use WebTorrent Desktop. I would rather have to switch to VLC myself, it is after all how VLC works by default, and your software should in no way alter VLC's default behavior. If anything, this is a VLC bug that you should NOT attempt to fix in this library.
