### ISSUE TITLE
Speed limit

### ISSUE THREAD

**Issue by Shankymahajan** [feross/webtorrent-desktop#718] opened 2016-07-16 14:15 UTC
The only thing now im missing in webtorrent is set download/upload speed limit .
I use my internet all the time but whenever I'm already using webtorrent ,i'm not able to browse properly .
I want to set my speed on webtorrent as a feature .

Thankyou !

**Comment by mathiasvr** [comment] 2016-07-16 15:56
Duplicate of #657

**Closed by mathiasvr** 2016-07-16 15:56 UTC
