### ISSUE TITLE
Support for Subs MKV Torrents in the player

### ISSUE THREAD

**Issue by robotrono** [feross/webtorrent-desktop#849] opened 2016-08-28 08:56 UTC
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.12

**What operating system and version?**
Windows 

**What did you do?**
I copy a torrent link

**What did you expect to happen?**
Play the torrent fine with subs.

**What actually happened?**
The torrent play very well, but dont show me the subs from a mkv file.

**Comment by demoneaux** [comment] 2016-08-28 09:17
This is a duplicate of#526, we’re currently trying to fix this.

**Closed by demoneaux** 2016-08-28 09:17 UTC
