### ISSUE TITLE
D'nt playing all video. Message Error and recommended VLC

### ISSUE THREAD

**Issue by SergeyDjam** [feross/webtorrent-desktop#1096] opened 2016-12-10 20:52 UTC
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.17.2

**What operating system and version?**
ROSA Linux Fresh x86_64

**What did you do?**
start playing all defalt videos and view console

[65:1210/234756:ERROR:sctpdataengine.cc(1050)] SctpDataMediaChannelFailed to send a stream reset for 1 streams: [0x00000009] Неправильный дескриптор файла

**What did you expect to happen?**

**What actually happened?**

**Comment by feross** [comment] 2017-01-18 10:46
Duplicate of https://github.com/feross/webtorrent-desktop/issues/350

**Closed by feross** 2017-01-18 10:46 UTC
