### ISSUE TITLE
WTD uses OS' Users folers If "Portable Settings" folder is existed

### ISSUE THREAD

**Issue by pureocean** [feross/webtorrent-desktop#971] opened 2016-09-26 20:00 UTC
**What version of WebTorrent Desktop?**
Version 0.17.0 (0.97.1) (64-bit)

**What operating system and version?**
Windows 10.0.10586 - (64-bit)

**What did you do?**
I only want to running in Portable mode of WebTorrent-Desktop (WTD). I always downloads the ZIP package of WTD.

**What did you expect to happen?**
Should be all settings in stores of "Portable Settings" folder if that folder is existed?

**What actually happened?**
Although the "_Portable Settings_" folder existed in extracted the folder of WTD, it's always creates/saves all settings,etc to in **%AppData%\WebTorrent** and **%LocalAppData%\WebTorrent**. I moves all file&subfolders to "_Portable Settings_" folder from this OS' Users folders. Unfortunately, WTD can't see/detect the "_Portable Settings_" and then again config.json and sub-folders creates in **%AppData%\WebTorrent** and **%LocalAppData%\WebTorrent**.

How I can be active complete portable mode without saving to %AppData% & %LocalAppData% folders? I wonder, is this a issue or else is removed portable support from WTD? I hope, unable to active portable-mode is my ignorance.

Sorry, my bad English.

**Comment by feross** [comment] 2016-09-27 03:32
This sounds like a bug. We definitely used to support "Portable Settings" correctly. I'll investigate.

**Comment by feross** [comment] 2016-09-27 05:55
I think I found the issue: https://github.com/feross/webtorrent-desktop/pull/974 This will be fixed in the next release. Really sorry about that!

**Comment by pureocean** [comment] 2016-09-27 06:08
@**feross**,

Please don't be sorry, really no need to apologize. Only human/software-condition...
Thank you very much your replies, interest,  investigates and the fix new. 
WTD improves build by build. I hope, it will be more known.

**Closed** 2016-09-27 18:47 UTC

**Comment by feross** [comment] 2016-09-27 19:57
Confirmed that the PR fixes the issue. Expect it to be out in the next release 👍

**Comment by feross** [comment] 2016-09-29 00:28
The app is also a lot better at leaving no trace on the user's hard disk when run as a portable app. The following files are no longer created:

- Disable Electron's single instance mode so no lock file is created in
"%APPDATA%\Roaming\WebTorrent".

- Put Electron crash files, and other electron files into the "Portable
Settings\Temp" folder instead of "%APPDATA%\Temp".

But that second fix isn't working correctly because of this Electron bug: https://github.com/electron/electron/issues/7399 Hope to have that fixed soon!

**Comment by feross** [comment] 2016-10-10 23:22
That last bug (crash files not getting stored in the correct location) is fixed in Electron now: https://github.com/electron/electron/pull/7500

So, this should be fixed once Electron does a release, and then WebTorrent does a release :)
