### ISSUE TITLE
Persistent UI failed to open file

### ISSUE THREAD

**Issue by dcposch** [feross/webtorrent-desktop#903] opened 2016-09-06 02:41 UTC
**WebTorrent version:** 0.14.0
**Electron version:** 1.3.3

Never seen this before, but it looks bad.

```
2016-09-05 19:30:55.128 Electron[1232:127615] Persistent UI failed to open file
file:///Users/dc/Library/Saved%20Application%20State/com.github.electron.savedState/window_2.data: 
Too many open files (24)
```

The app also quit without saving `config.json` later:

```
Saving state took too long. Quitting.
```

Ran from a development branch (ed872f8) using `npm start`

**Comment by demoneaux** [comment] 2016-09-28 04:10
According to [Google](https://www.google.com/search?q=persistent+UI+failed+to+open+file), this seems to be a pretty weird bug that occurs occasionally in OS X with no clear root cause. I think it's probably a one-time-only kind of bug.

**Comment by feross** [comment] 2016-10-05 09:41
Looks like we might have run out of file descriptors?

Closing because this seems impossible to reproduce. If more info arises, we can re-open it.

**Closed by feross** 2016-10-05 09:41 UTC
Labels: bug
