### ISSUE TITLE
Customizing Download/upload speeds

### ISSUE THREAD

**Issue by DragonzMaster** [feross/webtorrent-desktop#1065] opened 2016-11-06 17:10 UTC
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
17.2
**What operating system and version?**
Win10 64x

First, I want to thank all of you for this project.
I have a metered connection and unfortunately I live on Mars and have a 2 Mbps connection so want to ask If you could add an option to customize/limit - Download/Upload speeds or at least pause seeding after finishing download as it really hurts my bandwidth.

**Comment by aurimus** [comment] 2016-11-08 14:30
+1

**Comment by feross** [comment] 2017-01-21 04:45
Duplicate of https://github.com/feross/webtorrent-desktop/issues/435

**Closed by feross** 2017-01-21 04:45 UTC
