### ISSUE TITLE
torrent handler registration broken? (windows)

### ISSUE THREAD

**Issue by anonymlol** [feross/webtorrent-desktop#791] opened 2016-08-20 15:46 UTC
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
v 0.11.0 (0.96.1)

**What operating system and version?**
Windows 10 Pro x64

**What did you do?**
Click on magnet link (tried with and without using the toggle)

**What did you expect to happen?**
Expected the browser to ask to open with webtorrent-desktop (at least show it as an option)

**What actually happened?**
Webtorrent-desktop wasn't in the "open with" app list (for both magnet and stream-magnet). Torrent files (.torrent) weren't registered properly either (still defaulted to my other torrent client).

**Comment by feross** [comment] 2016-08-21 01:47
Was this a fresh install of WebTorrent Desktop? Or did you upgrade from a previous version?

We made a change in v0.11.0 to stop registering the app as the default handler until the user selects that option in the Preferences. Can you try that and see if it works for you?

**Comment by anonymlol** [comment] 2016-08-21 02:37
I had an older version and ran the installer to install v0.11.0. I tried the option in the preferences (the toggle I mentioned), it doesn't work.

**Comment by demoneaux** [comment] 2016-08-25 09:47
I’m able to confirm this on Windows 10. Not too sure what’s wrong with the code though, will look through it.

**Comment by henrypijames** [comment] 2016-09-01 08:59
Also confirm for WTD 0.12.0 (0.96.3) fresh install (non-portable) on Windows 10 x64.

Nothing happens (no change in the Windows Registry), not even when running WTD as an administrator.

**Comment by anonymlol** [comment] 2016-09-16 09:47
Seems to be fixed with v.0.15, same as #911.

**Comment by feross** [comment] 2016-10-05 09:34
Duplicate of https://github.com/feross/webtorrent-desktop/issues/911

**Closed by feross** 2016-10-05 09:34 UTC
Labels: bug
