### ISSUE TITLE
Video plays blank with sound.

### ISSUE THREAD

**Issue by solancer** [feross/webtorrent-desktop#564] opened 2016-05-22 21:41 UTC
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.5.1 (0.93.4)
**What operating system and version?**
Ubuntu 14.04 LTS
**What did you do?**
Tried playing a MKV torrent
**What did you expect to happen?**
Play the video
**What actually happened?**
Video plays blank with sound

**Comment by feross** [comment] 2016-05-23 06:49
This is caused by using H265 (HEVC) or another unsupported video codec.

This is fixed now, thanks to https://github.com/feross/webtorrent-desktop/issues/564. You'll now see a message about using VLC when a HEVC video is detected.

This will go out in the next release of WebTorrent (v0.6).

**Closed by feross** 2016-05-23 06:49 UTC
