### ISSUE TITLE
If torrent contains multiple files, all of them are being downloaded instead of the one that I chose to be played

### ISSUE THREAD

**Issue by ethaniel** [feross/webtorrent-desktop#658] opened 2016-06-20 17:59 UTC
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.7.2

**What operating system and version?**
Mac OS X El Capitan

**What did you do?**
Opened a magnet link which led to a torrent which contained many files.
Each file was an episode. There were 10 files. I click "play" at the first file.

**What did you expect to happen?**
Only the first file to be downloaded and played.

**What actually happened?**
All 10 files were downloaded in the background, wasting my bandwidth, while I was playing the first episode.

**Comment by demoneaux** [comment] 2016-06-21 00:42
Hi @ethaniel! This issue is a duplicate of #362, so we’re closing this for now!

**Closed by demoneaux** 2016-06-21 00:42 UTC
