### ISSUE TITLE
Cannot find module volume.node  on npm run package 

### ISSUE THREAD

**Issue by alamcordeiro** [feross/webtorrent-desktop#767] opened 2016-08-06 14:33 UTC
**What version of WebTorrent Desktop?** 0.10.0

**What operating system and version?** MacOS Sierra

**What did you do?** npm run package (after npm install success)

**What did you expect to happen?** Create packages (zip, dmg, ...)

**What actually happened?** Error: Cannot find module '../build/Release/volume.node (node_modules/macos-alias/lib/create.js:7:13)

**My solution:**
```
$ cd node_modules/macos-alias

$ npm install -g node-gyp

$ node-gyp rebuild

$ npm run package 
```

**Comment by feross** [comment] 2016-08-06 21:39
It looks like this error is caused by `appdmg` (the package that creates .dmg files) not supporting your version of Node.js. It could also be that MacOS Sierra is not supported by the tool.

What version of Node.js do you have installed? With the latest version (6.3.1) I have no trouble packaging the app on El Capitan. Going to close this since it works for me.

Do leave a comment if you figure out the cause of the issue.

**Closed by feross** 2016-08-06 21:39 UTC
Labels: question

**Comment by alamcordeiro** [comment] 2016-08-06 22:53
OK, my node version is 6.3.0
Try update to 6.3.1
