### ISSUE TITLE
WebTorrent cannot be selected as default app in Windows 10

### ISSUE THREAD

**Issue by pepjo** [feross/webtorrent-desktop#1021] opened 2016-10-07 19:51 UTC
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.17.1 (0.97.2) (64-bit)

**What operating system and version?**
Windows 10 - 1607

**What did you do?**
Click on a magnet link in my browser

**What did you expect to happen?**
Open webtorrent

**What actually happened?**
Nothing

-----
Also, In preferences it says:
"WebTorrent is your default torrent app. Horray!"

I've tried reinstalling, didn't work

I've tried going to windows defaults and webtorrents does not appear as an option. On the following screenshot you can see that only chrome and "Search in the store" options appear.
![image](https://cloud.githubusercontent.com/assets/1307305/19203497/e2608aa4-8cd7-11e6-9423-ab7a791293af.png)

I guess that WebTorrent is not reporting correctly the files that can open :/

**Comment by bluelovers** [comment] 2016-10-11 22:02
webtorrent update engin make new version folder every time when update to new release
so old exe path not exists

but didn't re-config uri-handler & default app
so always fail when new update out

and didn't give us a force re-config button

**Comment by demoneaux** [comment] 2016-10-12 11:55
Thanks for the report @bluelovers! We're currently trying to fix this over at #997.

**Comment by feross** [comment] 2016-10-13 03:37
@pepjo Sorry you're experiencing this. We'll try to fix this in the next version of WebTorrent.

Closing as duplicate of https://github.com/feross/webtorrent-desktop/issues/911

**Closed by feross** 2016-10-13 03:37 UTC

**Comment by bluelovers** [comment] 2016-10-15 01:22
@demoneaux i reported this long time before, just it never fixed at new vesion

**Comment by feross** [comment] 2017-01-17 00:28
@bluelovers I want to fix this issue before we release WebTorrent Desktop 1.0. Sorry it's taking a while. This will happen eventually.

**Comment by bluelovers** [comment] 2017-01-17 02:34
@feross i think is `if (state.unsaved.prefs.isFileHandler !== state.saved.prefs.isFileHandler)`

should chk ( FileHandler, Protocol ) when start up or open option window , not use exists cached prefs

i tryed fixed this before, but it make code looks not pretty
