### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by andreapaiola** [feross/webtorrent-desktop#347] opened 2016-04-07 11:17 UTC
Do you want .srt (or others formats?) support?

Like in [Niagara](https://andreapaiola.name/niagara/)

Let me know if you're interested...

**Comment by rom1504** [comment] 2016-04-07 12:16
duplicate of #281

**Comment by feross** [comment] 2016-04-08 04:37
@andreapaiola Yeah! This is a very important feature (based on the number of times I've heard folks request it). Let's discuss further on #281.

**Closed by feross** 2016-04-08 04:37 UTC
