### ISSUE TITLE
Start a torrent with a subtitle / Window Style

### ISSUE THREAD

**Issue by gabrieldesouza** [feross/webtorrent-desktop#705] opened 2016-07-05 17:49 UTC
Its possible start a torrent with a subtitle(without the user to specify it) if i have the .srt link ?

And is possible change the window style ( leave like mac example) with css in webtorrent ?

I'm using windows 8.1.
Latest version of webtorrent.

**Comment by mikeal** [comment] 2016-07-06 03:44
It would also be great if it played with subtitles embedded in the format like .mkv files do.

**Comment by dcposch** [comment] 2016-07-16 20:30
@mikeal i agree. the `<video>` tag doesn't support this out of the box yet, but we can probably hack it with https://www.npmjs.com/package/mkv-subtitle-extractor and mp4box.js

**Comment by feross** [comment] 2016-07-29 05:56
> @mikeal It would also be great if it played with subtitles embedded in the format like .mkv files do.

Yes -- this is something we should do! @mathiasvr, who is a WebTorrent Desktop contributor, actually wrote a subtitle parser that can extract subtitles from .mkv files: https://www.npmjs.com/package/matroska-subtitles

> @gabrieldesouza And is possible change the window style ( leave like mac example) with css in webtorrent ?

Sorry, no. If you want to improve the UI, you can send a PR though.

**Comment by feross** [comment] 2016-07-29 05:56
Closing as duplicate of https://github.com/feross/webtorrent-desktop/issues/526

**Closed by feross** 2016-07-29 05:56 UTC
