### ISSUE TITLE
Can't play .avi file

### ISSUE THREAD

**Issue by jankeromnes** [feross/webtorrent-desktop#627] opened 2016-06-05 11:21 UTC
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

Version 0.7.2 (0.94.3)

**What operating system and version?**

Windows 10

**What did you do?**

Trying playing a `.avi` video while downloading.

**What did you expect to happen?**

Playback starts.

**What actually happened?**

WebTorrent says "Error: Sorry, we can't play that file".

Furthermore, clicking on "Play in VLC" fails too (trying to play "http://localhost:60980/0"), but when I go to the file location, I can play it back in VLC without problem (the actual file, not the URL).

**Comment by jankeromnes** [comment] 2016-06-05 11:24
Update: Now that I'm over 15% downloaded, the "Play in VLC" feature works (VLC appears to be remote controlled by WebTorrent and plays back the video), but WebTorrent itself is still not able to play the stream.

**Comment by jankeromnes** [comment] 2016-06-05 12:11
And now when I click to play any of the downloading movies (Sintel, Tears of Steel, etc.) the playback times out, even though the movies are 40% and 72% complete.

**Comment by feross** [comment] 2016-06-06 00:44
WebTorrent Desktop can't play certain codecs, and when we detect those situations, we prompt you to use VLC.

The bug where it's not working until you get to 15%, and where the other torrents stop working is not correct behavior. There is probably an error or exception in the logs.

Can you try to reproduce this error once more? But this time when it happens, click View > Developer > Developer Tools, select the Console tab and copy-paste all the text into a new comment here.

Being able to see that output would help us out very much. Thanks.

**Comment by feross** [comment] 2016-08-06 05:10
@jankeromnes The behavior you're describing (where playback times out) is due to an uncaught exception. We've fixed a bunch of these in the most recent version of WebTorrent Desktop (0.10.0) so you can try updating and see if that fixes your issue.

If you see a similar issue in the future, you can click View > Developer > Developer Tools, select the Console tab and copy-paste all the text into a new issue here.

Going to close this now due to a lack of new information.

**Closed by feross** 2016-08-06 05:11 UTC
Labels: need more info

**Comment by jankeromnes** [comment] 2016-08-10 12:24
@feross Thanks a lot for telling me about the Developer Console, I retried with the Console open, but I wasn't able to reproduce, so I guess the underlying problems have been fixed. Thanks again!
