### ISSUE TITLE
Need a speed limit

### ISSUE THREAD

**Issue by ethaniel** [feross/webtorrent-desktop#657] opened 2016-06-20 17:09 UTC
Since we are technically cheating the torrent system, let's not add unnecessary load on the peers.
Set a default limit of 2 Megabytes / sec and let the users tune it to their needs.

**Comment by dcposch** [comment] 2016-06-23 01:17
Why are we "cheating the torrent system"? WebTorrent Desktop seeds every torrent you add, and by default it keeps seeding after you finish streaming. With minimize-to-tray, it keeps seeding even after you close the window.

I think WTD is a good citizen on the BitTorrent network.

(We probably *do* want to add bandwidth limiting, but that's for users on shared or metered internet connections, not to avoid abusing the network.)

**Comment by dcposch** [comment] 2016-06-23 01:37
@ethaniel I think a ratio limit would be enough, right?

If you limit your ratio to 1.0, you'd be guaranteed that if you stream 5GB of media, you use at most 5GB of upload bandwidth. That's good for people with metered connections.

If #435 solves the problem for you, feel free to close this issue, otherwise LMK why not

**Comment by ethaniel** [comment] 2016-06-23 05:25
Here is an outline on why we are cheating.

Why sequential downloading (what powers the "play now" feature) is bad: https://wiki.vuze.com/w/Sequential_downloading_is_bad

I am talking about an actual speed limiter, which would let me tune download/upload speeds, not the ratio. This feature is available in all torrent clients.

**Comment by quicoto** [comment] 2016-06-29 17:16
Also when using this on a home network, it might take all the bandwidth. The rest of the devices have a hard time using the Internet.

**Comment by feross** [comment] 2016-07-27 04:41
Throttling is a good idea -- on connections with a speed cap, it's important not to have one app use all the bandwidth.

@ethaniel That wiki page is out-of-date.

With the speed of today’s home internet connections, the user is going to finish fully downloading the torrent in a fraction of the time it takes to view it, so they will still spend more time seeding than downloading.

We’re also going to improve the algorithm to switch back to a rarest-first strategy when there is not a high-priority need for specific pieces. In other words, when sufficient video is buffered, there’s no need to deviate from the default piece selection algorithm. So it won't spend that much time in sequential-first mode.

@quicoto Yes, this is another reason that throttling is useful.

**Comment by feross** [comment] 2016-08-08 06:54
Closing as duplicate of #435

**Closed by feross** 2016-08-08 06:54 UTC
Labels: feature request
